# General Configuration
server.port=9001
spring.application.name=SpringBootAws
spring.profiles.active=local

#spring.cloud.aws.region.static=us-east-1
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health

logging.file.path=/app/logs
logging.file.name=app.log
