spring:
  cloud:
    aws:
      sqs:
        enabled: true
        listener:
          queue-not-found-strategy: FAIL # IGNORE / FAIL
          resolution-strategy: resolve
          max-number-of-messages: 10
          concurrency: 5
      # REMOVE credentials.instance-profile: true
  flyway:
    locations: "classpath:db/migration/{vendor}"
    baseline-on-migrate: true
    