aws.region=us-east-1
aws.s3.bucket=s3-java-pgm-mybucket

# Database configuration for test profile
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
