services:
  my-app:
    image: springboot-app:latest
    container_name: my-boot-app
    privileged: true  # Simplest way for EC2 to see newly attached USB/IP devices
    volumes:
      - "/dev:/dev"   # Maps the entire /dev to handle dynamic USB/IP attaches
      - "/home/ec2-user/app-logs:/app/logs"
    ports:
      - "9001:9001"
    environment:
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:ACC_NO:my-topic
      - SPRING_CLOUD_AWS_REGION_STATIC=us-east-1
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_AWS_CREDENTIALS_INSTANCE_PROFILE=true
      - LOGGING_FILE_NAME=/app/logs/app.log
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-single-az-db.ce3i02g225kv.us-east-1.rds.amazonaws.com:3306/app_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=*****
    restart: unless-stopped
