server.port=9001
spring.application.name=SpringBootDocker

# Spring Boot automatically maps these to the -e flags in docker run
spring.datasource.url=jdbc:h2:file:./target/sampledb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update